[package]
edition = "2021"
name = "zome_2_types"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdi = "0.2"
serde = "1"
